-- generated by scripts/build-explanations.js
insert into explanations (skill_id, body) values ('5.MP.1', '# Choose a strategy, show working, estimate first, check reasonableness, explain reasoning (5.MP.1, MP1/MP3/MP6)

## The idea (in small steps)
1. Before calculating, estimate: round the numbers to friendly ones and work it out in your head. This gives you a "should be about" number.
2. Choose a strategy that fits the numbers: split by place value, use a known fact, use the inverse, draw a model.
3. Show every step on paper so you (and the coach) can find exactly where a mistake happens.
4. After calculating, compare with the estimate. If they are far apart, something went wrong — check.
5. Explain the reasoning in a sentence using the right words: "I rounded 48 to 50 because…", "I multiplied first because…".

## Worked example
23 × 297 — Rasim got 6,847. Estimate: 20 × 300 = 6,000. 6,847 is close to 6,000 (a bit more, and 23 × 297 should be a bit more than 20 × 300), so it is reasonable. If he had written 68,470 the estimate would show it is ten times too big. Explanation: "I rounded both numbers and multiplied; the answer is near my estimate, so it is reasonable."

## Faded example (he completes)
Estimate 48 × 21: round to ___ × ___ = ___ . Now the exact answer 1,008 — is it reasonable? ___ because ___ . (Answers: 50 × 20 = 1,000; yes, it is close to 1,000.)

## Anticipated errors (and the scaffold)
- Skipping the estimate because "I know how to do it". Scaffold: "Estimate first, every time — it takes five seconds."
- Explaining with "I just did it". Scaffold: "Tell me the first thing you did and why."
- Rounding in the wrong direction or to the wrong place. Scaffold: "Which ten is 48 nearest to?"
- Treating "reasonable" as "exactly equal". Scaffold: "Close, not equal — how close is close enough here?"

## Representation sequence
1. Words: the three-step chant — estimate, calculate, compare.
2. Picture: a number line showing the estimate and the exact answer close together (or far apart).
3. Table: problem | estimate | answer | reasonable? | why.
4. Story: shopping — "about 50 manat" before paying, then the receipt.
5. Teach it: he checks the coach''s deliberately wrong answer using an estimate.

## Check by explaining back
"Why do mathematicians estimate before they calculate?"') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('5.NBT.1', '# Place-value relationships: 10× and 1/10 of adjacent places (5.NBT.1, 5.NBT.A.1)

## The idea (in small steps)
1. Every place in a number is worth ten times the place to its right. Hundreds are ten times tens; thousands are ten times hundreds.
2. Going the other way, every place is one tenth of the place to its left.
3. The same digit can be worth very different amounts: in 5,550 the left 5 is 5,000, the middle 5 is 500, the right 5 is 50.
4. To compare two digits, write their values and ask "how many times bigger?" 5,000 ÷ 500 = 10.
5. This is why moving a digit one place left multiplies its value by 10, and one place right divides by 10.

## Worked example
In 5,550: the 5 in the hundreds place is worth 500; the 5 in the thousands place is worth 5,000. 5,000 is 10 times 500, so the thousands 5 is 10 times the hundreds 5. The hundreds 5 is one tenth of the thousands 5.

## Faded example (he completes)
In 7,070: the 7 in the tens place is worth ___; the 7 in the thousands place is worth ___. ___ ÷ ___ = ___, so the thousands 7 is ___ times the tens 7. (Answers: 70; 7,000; 7,000 ÷ 70 = 100; 100 times — two places apart.)

## Anticipated errors (and the scaffold)
- Saying "the 5s are the same". Scaffold: "Same digit — is it in the same place? What is each one worth?"
- Answering 2 or "two places" instead of 100 for two places apart. Scaffold: "10 for one step, 10 × 10 for two steps."
- Mixing up ×10 and ÷10 direction. Scaffold: "Left is bigger. Which way did you move?"
- Reading 1/10 as 10. Scaffold: write the fraction and the value side by side.

## Representation sequence
1. Words: "each place is ten of the one to its right".
2. Picture: a place-value chart with the digit written in two columns; arrows labelled ×10 / ÷10.
3. Table: place | value of the digit | ratio to the next place.
4. Story: money — a 10-manat note is ten 1-manat coins; a 100-manat note is ten 10s.
5. Teach it: he explains to a younger child why 5,000 is "ten of 500".

## Check by explaining back
"What happens to a digit''s value when it moves one place to the left? And to the right?"') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('5.NBT.2', '# Powers of 10 with exponents; multiply and divide by powers of 10 (5.NBT.2, 5.NBT.A.2)

## The idea (in small steps)
1. 10 × 10 × 10 is written 10³. The small number (the exponent) counts how many tens are multiplied.
2. 10³ = 1,000: a 1 followed by 3 zeros. The exponent tells you the number of zeros.
3. Multiplying by 10ⁿ moves every digit n places to the left (the number gets bigger); the empty places fill with zeros.
4. Dividing by 10ⁿ moves every digit n places to the right (smaller).
5. For 30 × 400: multiply the front digits (3 × 4 = 12), then attach the zeros from both numbers (1 + 2 = 3 zeros) → 12,000.

## Worked example
37 × 100: 100 = 10², so every digit moves two places left: 37 → 3,700. Check: 37 hundreds is 3,700. And 4,500 ÷ 10²: move two places right: 4,500 → 45.

## Faded example (he completes)
6 × 10³: 10³ = ___, so 6 × ___ = ___. Then 30 × 400: 3 × 4 = ___, zeros to attach: ___, answer ___. (Answers: 1,000; 6,000; 12; 3; 12,000.)

## Anticipated errors (and the scaffold)
- Reading 10³ as 10 × 3 = 30. Scaffold: "The exponent counts tens multiplied, not added."
- "Add a zero" for ×10 works for whole numbers but fails later with decimals. Scaffold: "digits move places; say it that way from now on."
- Losing a zero in 30 × 400 (getting 1,200). Scaffold: "Count the zeros in both numbers before you start."
- Confusing which way to move for ÷. Scaffold: "Dividing makes it smaller, so the digits move right."

## Representation sequence
1. Words: "the exponent counts the zeros".
2. Picture: place-value chart with digits sliding left or right by n boxes.
3. Table: 10¹, 10², 10³, 10⁴ with their values and zero counts.
4. Story: 3 boxes of 400 grams; 30 boxes of 400 grams.
5. Teach it: he explains why 6 × 10³ has more zeros than 6 × 10².

## Check by explaining back
"What does the 4 in 10⁴ tell you? What happens to 37 when you multiply it by 10⁴?"') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('5.NBT.5', '# Multiply multi-digit whole numbers with the standard algorithm (5.NBT.5, 5.NBT.B.5)

## The idea (in small steps)
1. Multiplying by a 2-digit number is two easier multiplications added together: 36 = 30 + 6, so 4,825 × 36 = 4,825 × 30 + 4,825 × 6.
2. Do the ones first: 4,825 × 6, working right to left and carrying.
3. Then the tens: 4,825 × 30. Because it is ×30, the row starts one place to the left — write a 0 in the ones place first, then multiply by 3.
4. Add the two rows. Estimate first (5,000 × 40 = 200,000) so you know the answer should be a bit less than that.

## Worked example
4,825 × 36. Ones row: 6 × 5 = 30, write 0 carry 3; 6 × 2 = 12 + 3 = 15, write 5 carry 1; 6 × 8 = 48 + 1 = 49, write 9 carry 4; 6 × 4 = 24 + 4 = 28. Row 1 = 28,950. Tens row: write 0, then 3 × 4,825 = 14,475, so row 2 = 144,750. Add: 28,950 + 144,750 = 173,700. Check against the estimate: close to 200,000 and a little less. Reasonable.

## Faded example (he completes)
327 × 24. Row 1: 327 × 4 = ___ . Row 2: write the 0, then 327 × 2 = 654, so the row is 6,540. Add: ___ + 6,540 = ___ . (Answers: 1,308; 7,848.)

## Anticipated errors (and the scaffold)
- Forgetting the 0 on the tens row → the second row is ten times too small. Scaffold: "What are you really multiplying by — 3 or 30?"
- Adding the carry before multiplying (6 × 2 then +3 is right; 6 × (2 + 3) is wrong). Scaffold: "Multiply first, then add the carry."
- Lining rows up wrongly. Scaffold: use squared paper, one digit per box.
- Not estimating, so a wrong answer looks fine. Scaffold: always round both numbers first.

## Representation sequence
1. Words: "two rows, ones then tens, then add".
2. Picture: an area model — a rectangle split into 4,000 + 800 + 20 + 5 across and 30 + 6 down; each cell is a partial product.
3. Table: the partial products listed and summed.
4. Story: 36 boxes of 4,825 pencils; 30 boxes plus 6 boxes.
5. Teach it: he explains to a "younger student" why the 0 goes on the second row.

## Check by explaining back
Ask: "Why does the second row start with a zero?" A secure answer mentions tens / ×30 / ten times bigger.') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('5.NBT.6a', '# Relate multiplication and division; use the inverse to check (5.NBT.6a, 5.NBT.B.6 intro)

## The idea (in small steps)
1. Multiplication and division undo each other. If 8 × 651 = 5,208, then 5,208 ÷ 8 = 651 and 5,208 ÷ 651 = 8.
2. A division has three parts: dividend ÷ divisor = quotient. Divisor × quotient = dividend.
3. To check a division, multiply the answer by the divisor. If you get the number you started with, the division is right.
4. If there is a remainder: divisor × quotient + remainder = dividend.
5. To find a missing dividend, work backwards: multiply, then add the remainder.

## Worked example
Kim says 5,208 ÷ 8 = 651. Check: 651 × 8. 600 × 8 = 4,800; 50 × 8 = 400; 1 × 8 = 8. Total 5,208. That equals the dividend, so Kim is right. If she had said 641, the check gives 5,128 ≠ 5,208 — wrong.

## Faded example (he completes)
A number divided by 7 gives 43 remainder 2. Number = 7 × ___ + ___ = ___ + 2 = ___ . (Answers: 43; 2; 301; 303.)

## Anticipated errors (and the scaffold)
- Checking a division with another division. Scaffold: "Undo it — what is the opposite of dividing?"
- Forgetting to add the remainder back. Scaffold: "The remainder was left over — put it back."
- Multiplying the dividend instead of the quotient (5,208 × 8). Scaffold: "Multiply the ANSWER by the divisor."
- Trusting the calculation without checking. Scaffold: "You are not done until the check matches."

## Representation sequence
1. Words: "divide, then multiply back".
2. Picture: fact triangle — 5,208 on top, 8 and 651 at the bottom corners.
3. Table: dividend | divisor | quotient | remainder | check.
4. Story: 5,208 sweets shared into 8 bags; multiply back to count them.
5. Teach it: he makes up a division, gets the coach to "answer" it wrongly, and catches the mistake with a check.

## Check by explaining back
"How can you be sure a division answer is right without asking anyone?"') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('5.NBT.RW', '# Read, write, compare and order whole numbers to billions; expanded form (5.NBT.RW, 5.NBT.A.1 ext.)

## The idea (in small steps)
1. Big numbers are read in groups of three digits called periods: billions, millions, thousands, ones. Commas separate the periods.
2. Read each period like a three-digit number, then say the period''s name: 2,046,300,015 = "two billion, forty-six million, three hundred thousand, fifteen".
3. Zeros are place holders: they keep the other digits in the right place even though you do not say them.
4. Expanded form writes the value of each non-zero digit and adds them: 830,207,000 = 800,000,000 + 30,000,000 + 200,000 + 7,000.
5. To compare numbers with the same number of digits, compare from the left, one place at a time; the first difference decides.

## Worked example
Order 4,090,000; 4,900,000; 4,009,000; 4,099,000. All start with 4 million. Look at the hundred-thousands: 0, 9, 0, 0 → 4,900,000 is largest. Among the rest, ten-thousands: 9, 0, 9 → 4,009,000 is smallest. Then thousands: 4,090,000 has 0, 4,099,000 has 9. Order: 4,009,000 < 4,090,000 < 4,099,000 < 4,900,000.

## Faded example (he completes)
Write in digits: "four hundred six thousand, twenty-nine". Thousands period: 406. Ones period: 029 (three digits!). Number: ___ . (Answer: 406,029.)

## Anticipated errors (and the scaffold)
- Dropping a placeholder zero: writing 406,29 or 46,029. Scaffold: "Each period has exactly three digits — pad with zeros."
- Comparing by "which has more nines". Scaffold: "Start from the left. Same? Move one place right."
- Expanded form with the wrong place value (30,000,000 written as 3,000,000). Scaffold: count the places after the digit.
- Saying "and" between periods. Scaffold: in English number names, "and" is only for decimals.

## Representation sequence
1. Words: period names as a chant.
2. Picture: a place-value chart with period columns coloured.
3. Table: digit | place | value, then add for expanded form.
4. Story: population of countries / distance to the Moon in metres.
5. Teach it: he dictates a number in words and checks the coach''s digits.

## Check by explaining back
"How do you decide which of two 7-digit numbers is bigger?"') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('5.OA.1', '# Evaluate expressions with parentheses, brackets, braces; order of operations (5.OA.1, 5.OA.A.1)

## The idea (in small steps)
1. An expression is a set of instructions. Everyone must follow the same order or they get different answers.
2. Grouping symbols first: ( ) inside [ ] inside { }. Work from the innermost group outwards.
3. Then × and ÷, left to right, whichever comes first.
4. Then + and −, left to right.
5. Rewrite the expression one step at a time on a new line, replacing only the part you just worked out.

## Worked example
[(18 − 6) ÷ 4] + 2 × 7. Innermost bracket: 18 − 6 = 12 → [12 ÷ 4] + 2 × 7. Square bracket: 12 ÷ 4 = 3 → 3 + 2 × 7. Multiply before add: 2 × 7 = 14 → 3 + 14 = 17.

## Faded example (he completes)
36 ÷ (2 + 4) × 5. Brackets: 2 + 4 = ___ → 36 ÷ ___ × 5. Divide (it comes first, left to right): 36 ÷ 6 = ___ → ___ × 5 = ___. (Answers: 6; 6; 30.)

## Anticipated errors (and the scaffold)
- Working strictly left to right: 8 + 4 × 3 = 36. Scaffold: "Which is stronger, × or +? Do the × first, then come back."
- Doing × before ÷ even when ÷ comes first (36 ÷ 6 × 5 as 36 ÷ 30). Scaffold: "× and ÷ are equals — read left to right."
- Dropping a bracket when rewriting. Scaffold: rewrite the whole expression each line; only replace the piece you solved.
- Confusing [ ] with a different rule. Scaffold: all grouping symbols mean "do me first"; the shapes just show nesting.

## Representation sequence
1. Words: "groups, then times and divide, then plus and minus".
2. Picture: draw a box around each group; solve from the inside box out, crossing out as you go.
3. Table: a two-column table — "expression now" | "what I did".
4. Story: a recipe where the bracket is "mix these first"; or money: 3 friends each get (2 + 5) manat.
5. Teach it: he corrects "Rasim''s mistake" (5 + 3 × 2 = 16) and explains why.

## Check by explaining back
Ask him to say the order in his own words and to give one example where left-to-right would go wrong.') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('5.OA.2', '# Write and interpret numerical expressions from words without evaluating (5.OA.2, 5.OA.A.2)

## The idea (in small steps)
1. The words tell you what happens first. Whatever happens first goes inside brackets if something else is done to the result.
2. "The sum of A and B" = A + B. "The difference between A and B" = A − B. "The product of A and B" = A × B. "Twice / three times" = × 2 / × 3.
3. "…, then multiply by C" means the whole first part is multiplied: (A + B) × C.
4. Read your expression back into words to check it says the same thing.
5. Do not calculate — the task is to write the instructions, not the answer.

## Worked example
"The sum of 12 and 8, multiplied by 3." First thing: the sum, 12 + 8. Then the whole sum is multiplied by 3, so brackets: (12 + 8) × 3. Read back: "twelve plus eight, all times three." Matches.

## Faded example (he completes)
"Subtract 6 from 40, then multiply by 5." First: 40 − ___ . Then times 5 on the whole thing: ( ___ ) × 5. (Answer: (40 − 6) × 5.)

## Anticipated errors (and the scaffold)
- Writing the numbers in the order heard: "subtract 6 from 40" as 6 − 40. Scaffold: "Which number do you start with? Which one is taken away?"
- Leaving out the brackets: 12 + 8 × 3. Scaffold: "Is only the 8 multiplied, or the whole sum?"
- Calculating instead of writing the expression. Scaffold: "Freeze — write the recipe, not the cake."
- Interpreting "3 × (18,932 + 921)" by computing it. Scaffold: "How does it compare with 18,932 + 921 without working it out?"

## Representation sequence
1. Words ↔ symbols: a two-column card, words on the left, expression on the right.
2. Picture: draw the bracket as a box; the operation outside acts on the whole box.
3. Table: key phrases (sum, difference, product, twice, half) and their symbols.
4. Story: "Aysel has 12 stickers and 8 more; her three friends each get the same amount" → (12 + 8) × 3 vs 12 + 8 × 3.
5. Teach it: he writes a words-puzzle for the coach to turn into an expression, then checks it.

## Check by explaining back
Ask him to explain, without numbers, when brackets are needed.') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('5.OA.PROP', '# Properties of operations: commutative, associative, distributive, identity (5.OA.PROP, Go Math 1.3)

## The idea (in small steps)
1. Commutative: swap the order, same answer. 7 × 5 = 5 × 7. Works for + and ×, not for − or ÷.
2. Associative: change the grouping, same answer. (7 × 5) × 2 = 7 × (5 × 2). The numbers stay in order; only the brackets move.
3. Distributive: split one number, multiply each part, then add. 6 × 48 = 6 × 40 + 6 × 8 = 240 + 48 = 288.
4. Identity: × 1 or + 0 leaves a number unchanged.
5. Properties are tools: use them to make hard calculations easy, and to check answers.

## Worked example
6 × 48 with the distributive property. Split 48 into 40 + 8 (tens and ones). 6 × 40 = 240. 6 × 8 = 48. Add: 240 + 48 = 288. Check by estimate: 6 × 50 = 300, so 288 is reasonable.

## Faded example (he completes)
(7 × 5) × 2 = 7 × (___ × 2). Which property? ___ . Then 4 × 27 = 4 × 20 + 4 × ___ = 80 + ___ = ___ . (Answers: 5; associative; 7; 28; 108.)

## Anticipated errors (and the scaffold)
- Calling every property "commutative". Scaffold: "Did the ORDER change, or the GROUPING, or did a number get SPLIT?"
- Distributing to only one part: 6 × 48 = 6 × 40 + 8. Scaffold: "Both parts of 48 need the 6."
- Thinking subtraction is commutative (8 − 3 = 3 − 8). Scaffold: test it with numbers.
- Splitting 48 into 4 + 8. Scaffold: "48 is 40 and 8, not 4 and 8."

## Representation sequence
1. Words: three questions — order? grouping? splitting?
2. Picture: area model for the distributive property — a 6 × 48 rectangle cut into 6 × 40 and 6 × 8.
3. Table: property | rule | example.
4. Story: 6 friends each buy 48 stickers — think of the packets of 40 and the loose 8.
5. Teach it: he invents one example of each property and names it.

## Check by explaining back
"Show me two different ways to work out 5 × 36 and tell me which property each one uses."') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('G4.NBT.1', '# Place value to 1,000,000: read, write, compare, round (G4.NBT.1, 4.NBT.A.1-3)

## The idea (in small steps)
1. Numbers up to a million have two periods: thousands and ones. 406,029 is "four hundred six thousand, twenty-nine".
2. Each digit has a place and a value. In 738,462 the 3 is in the ten-thousands place and is worth 30,000.
3. To round to a place, look at the digit just to the right of that place: 5 or more → round up; less than 5 → keep. Everything to the right becomes 0.
4. To compare, line up the places; compare from the left; the first different digit decides.
5. Zeros hold places: "four hundred six thousand" has a 0 in the tens-of-thousands? No — 406 thousand: 4 hundred-thousands, 0 ten-thousands, 6 thousands.

## Worked example
Round 738,462 to the nearest ten thousand. The ten-thousands digit is 3. Look right: 8. 8 ≥ 5, so round up: 3 becomes 4, and everything to the right becomes 0 → 740,000. Check on a number line: 738,462 is between 730,000 and 740,000 and closer to 740,000.

## Faded example (he completes)
Round 52,349 to the nearest thousand. Thousands digit: ___. Digit to its right: ___. Round up or keep? ___ . Answer: ___ . (Answers: 2; 3; keep; 52,000.)

## Anticipated errors (and the scaffold)
- Rounding the wrong place (to the nearest thousand when asked for ten thousand). Scaffold: underline the target digit first.
- "Rounding up" by changing several digits. Scaffold: "Only the target digit can change; the rest become zeros."
- Writing words as digits without placeholder zeros (46,029 for 406,029). Scaffold: "Say the thousands period as a 3-digit number: four hundred SIX = 406."
- Comparing by the first digit only. Scaffold: "Same first digit? Slide one place right."

## Representation sequence
1. Words: place names in order; the "5 or more" rule as a chant.
2. Picture: a number line between the two round numbers; where does the number sit?
3. Table: a place-value chart, the target digit circled.
4. Story: a stadium holds 52,349 people — "about how many?" for a newspaper headline.
5. Teach it: he explains rounding to a younger child using the number line.

## Check by explaining back
"How do you know whether to round up or down?"') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('G4.NBT.2', '# Add and subtract multi-digit numbers with regrouping (G4.NBT.2, 4.NBT.B.4)

## The idea (in small steps)
1. Line up the places: ones under ones, tens under tens. Squared paper helps.
2. Add or subtract from the right (ones) to the left.
3. Adding: if a column makes 10 or more, write the ones digit and carry 1 to the next column.
4. Subtracting: if the top digit is smaller, borrow 1 from the next place to the left (it becomes 10 in this column).
5. Borrowing across a zero: you cannot borrow from 0, so borrow from the next non-zero place first; the 0 becomes 9 (10 minus the 1 you passed on).
6. Check subtraction by adding back: answer + the number you took away = the number you started with.

## Worked example
60,304 − 27,856. Ones: 4 − 6 cannot do. The tens digit is 0, so go to hundreds: 3 becomes 2, the tens 0 becomes 10, borrow one to the ones: tens 9, ones 14. 14 − 6 = 8. Tens: 9 − 5 = 4. Hundreds: 2 − 8 cannot do; borrow from thousands (0 → go to ten-thousands: 6 → 5, thousands 0 → 10 → 9, hundreds 12). 12 − 8 = 4. Thousands: 9 − 7 = 2. Ten-thousands: 5 − 2 = 3. Answer 32,448. Check: 32,448 + 27,856 = 60,304.

## Faded example (he completes)
5,003 − 1,247. Ones: 3 − 7 cannot do; borrow across the zeros: thousands 5 → ___, hundreds 0 → ___, tens 0 → ___, ones 3 → ___ . Now subtract each column: ___ . (Answers: 4; 9; 9; 13; 3,756.)

## Anticipated errors (and the scaffold)
- Subtracting the smaller digit from the larger regardless of position (6 − 4 instead of 4 − 6). Scaffold: "Top minus bottom. Can you? If not, borrow."
- Forgetting to reduce the digit you borrowed from. Scaffold: cross out and rewrite the digit before moving on.
- Borrowing from a 0 and leaving it as 0. Scaffold: "You cannot borrow from nothing — go one more place left."
- Misaligned columns. Scaffold: squared paper, commas lined up.

## Representation sequence
1. Words: the column chant — "can I? if not, borrow".
2. Picture: place-value blocks; trading a hundred for ten tens.
3. Table: the column algorithm on squared paper with the crossings-out shown.
4. Story: 60,304 manat in the bank, 27,856 spent.
5. Teach it: he explains borrowing across a zero to a younger child using blocks.

## Check by explaining back
"What do you do when you have to subtract from a zero?"') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('G4.NBT.3', '# Multiply up to 4-digit by 1-digit and 2-digit by 2-digit (G4.NBT.3, 4.NBT.B.5)

## The idea (in small steps)
1. Break the big number by place value and multiply each part: 3,246 × 7 = 3,000×7 + 200×7 + 40×7 + 6×7.
2. The column method does the same thing right to left with carrying: 6 × 7 = 42, write 2 carry 4; 4 × 7 = 28 + 4 = 32, write 2 carry 3; and so on.
3. Two-digit × two-digit: split the second number into tens and ones, get two rows, add them. 46 × 23 = 46 × 20 + 46 × 3.
4. Estimate first: 3,246 × 7 ≈ 3,000 × 7 = 21,000; 46 × 23 ≈ 50 × 20 = 1,000.
5. In word problems, find the two numbers that multiply and ignore numbers that are not needed.

## Worked example
46 × 23. Row 1 (ones): 46 × 3 = 138. Row 2 (tens): 46 × 20 = 920. Add: 138 + 920 = 1,058. Estimate check: about 1,000. Reasonable.

## Faded example (he completes)
3,246 × 7 by columns: 6 × 7 = 42 → write 2, carry ___. 4 × 7 = 28 + ___ = ___ → write 2, carry 3. 2 × 7 = 14 + 3 = ___ → write 7, carry 1. 3 × 7 = 21 + 1 = ___ . Answer: ___ . (Answers: 4; 4; 32; 17; 22; 22,722.)

## Anticipated errors (and the scaffold)
- Adding the carry before multiplying. Scaffold: "Multiply first, THEN add the carry."
- In 2×2, multiplying only the ones (46 × 3) and stopping. Scaffold: "23 is 20 and 3 — where is the 20 row?"
- Forgetting the 0 in the tens row. Scaffold: "You are multiplying by 20, so the row ends in 0."
- Using a distractor number from the story. Scaffold: "Which numbers answer the question? Cross out the rest."

## Representation sequence
1. Words: "split by place, multiply each, add".
2. Picture: area model — a 46 × 23 rectangle cut into 40×20, 40×3, 6×20, 6×3.
3. Table: partial products listed and summed.
4. Story: 23 boxes of 46 pencils.
5. Teach it: he draws the area model for a younger child.

## Check by explaining back
"Why are there two rows when you multiply by 23?"') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('G4.NBT.4', '# Divide up to 4-digit by 1-digit with remainders (G4.NBT.4, 4.NBT.B.6)

## The idea (in small steps)
1. Division asks "how many groups of this size?" 2,957 ÷ 6: how many sixes in 2,957, and what is left over?
2. Long division works place by place from the left: thousands, hundreds, tens, ones. At each step: divide, multiply, subtract, bring down.
3. If a digit is too small to divide, write 0 in the answer and bring down the next digit.
4. Whatever is left at the end and is smaller than the divisor is the remainder. Write it as "492 r 5".
5. Check: divisor × quotient + remainder = the number you started with.

## Worked example
2,957 ÷ 6. 2 thousands: too small for 6 → look at 29 hundreds. 6 × 4 = 24, write 4, 29 − 24 = 5, bring down 5 → 55. 6 × 9 = 54, write 9, 55 − 54 = 1, bring down 7 → 17. 6 × 2 = 12, write 2, 17 − 12 = 5. No more digits: remainder 5. Answer 492 r 5. Check: 6 × 492 = 2,952, + 5 = 2,957.

## Faded example (he completes)
1,384 ÷ 4. 1 is too small; 13 ÷ 4 = ___ r 1; bring down 8 → 18 ÷ 4 = ___ r 2; bring down 4 → 24 ÷ 4 = ___ . Answer ___ . (Answers: 3; 4; 6; 346.)

## Anticipated errors (and the scaffold)
- Forgetting the 0 in the quotient when a digit is too small (writing 46 instead of 406). Scaffold: "Every digit you bring down needs a digit in the answer."
- Remainder bigger than the divisor. Scaffold: "If the leftover is 6 or more, one more group fits."
- Not checking. Scaffold: multiply back before saying you are done.
- In word problems: rounding the wrong way (buses: round up; full boxes: round down). Scaffold: "What does the remainder mean here?"

## Representation sequence
1. Words: divide, multiply, subtract, bring down — "Does McDonald''s Sell Burgers?"
2. Picture: sharing base-ten blocks into 6 groups, trading when needed.
3. Table: the long-division layout step by step.
4. Story: 2,957 sweets into 6 bags; how many each, how many left?
5. Teach it: he narrates each step aloud for a younger child.

## Check by explaining back
"What do you do when the digit you bring down is smaller than the divisor?"') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('G4.OA.2', '# Multi-step word problems with all four operations; interpret remainders (G4.OA.2, 4.OA.A.3)

## The idea (in small steps)
1. Read the question last sentence first: what exactly is being asked? Underline it.
2. Find the numbers that matter and what each one is. Cross out numbers that do not help.
3. Plan the steps in words before calculating: "first total, then given out, then left over".
4. Do one step at a time, label each result ("total = 360").
5. Estimate the final answer and check it makes sense for the story (pencils cannot be negative or a fraction).
6. Remainders: decide whether to round up (buses needed), round down (full boxes), or use the remainder itself (left over).

## Worked example
A box holds 24 pencils. A school buys 15 boxes and gives 9 pencils to each of 32 students. How many are left? Ask: left over. Step 1: total = 24 × 15 = 360. Step 2: given out = 9 × 32 = 288. Step 3: left = 360 − 288 = 72. Estimate: 25 × 15 ≈ 375, 9 × 30 ≈ 270, about 100 left. 72 is reasonable.

## Faded example (he completes)
Aysel buys 3 packs of 8 pens and 5 loose pens. Step 1: 3 × 8 = ___ . Step 2: ___ + 5 = ___ . (Answers: 24; 24 + 5 = 29.)

## Anticipated errors (and the scaffold)
- Using every number in the story, including the distractor. Scaffold: "What does this number tell us? Do we need it to answer the question?"
- Doing one step and stopping. Scaffold: "Have you answered the question in the last sentence?"
- Picking the operation from a keyword ("more" → add) instead of the situation. Scaffold: "Act it out — is something being joined, taken away, shared or repeated?"
- Reporting a remainder without deciding what it means. Scaffold: "Can half a bus exist?"

## Representation sequence
1. Words: the four questions — what is asked, what do I know, what is the plan, is it reasonable.
2. Picture: bar model — a long bar for the total, shaded for the part given out.
3. Table: step | calculation | result | what it means.
4. Story: he retells the problem in his own words with the numbers in the right roles.
5. Teach it: he writes a two-step problem with one distractor number for the coach to solve.

## Check by explaining back
"Which number in that problem was not needed, and how did you know?"') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('G4.OA.F', '# Multiplication and division facts to 12 × 12, fluent (G4.OA.F, 3.OA.C.7)

## The idea (in small steps)
1. Fluent means fast and correct without counting: under 3 seconds a fact. That comes from strategy first, then practice.
2. Anchor facts: ×2 (double), ×5 (half of ×10), ×10, ×11 (repeat the digit), and the squares (6×6, 7×7, 8×8, 9×9).
3. Derive the rest from anchors: 7 × 8 = 7 × 4 doubled = 28 × 2 = 56; 6 × 9 = 6 × 10 − 6 = 54; 12 × 7 = 10 × 7 + 2 × 7 = 84.
4. Every multiplication fact gives two division facts: 7 × 8 = 56 → 56 ÷ 7 = 8 and 56 ÷ 8 = 7.
5. Practise the hard six daily: 6×7, 6×8, 7×8, 7×9, 8×9, 6×9. Say them, don''t count.

## Worked example
9 × 9: an anchor square, 81. 11 × 12: 11 × 12 = 10 × 12 + 12 = 120 + 12 = 132. 8 × 4: double 8 twice: 16, 32. 56 ÷ 7: "7 times what is 56?" 7 × 8 — so 8.

## Faded example (he completes)
7 × 9 = 7 × 10 − ___ = 70 − ___ = ___ . So 63 ÷ 7 = ___ . (Answers: 7; 7; 63; 9.)

## Anticipated errors (and the scaffold)
- Counting on fingers in threes/sevens — correct but slow. Scaffold: "Which anchor is closest? Derive from it."
- Mixing 7 × 8 = 54 / 6 × 9 = 56 (swapped). Scaffold: "56 = 7 × 8: five, six, seven, eight."
- Freezing when timed. Scaffold: practise untimed until correct, then add the timer gradually.
- Treating division facts as separate. Scaffold: "Turn it into a times question."

## Representation sequence
1. Words: fact families said aloud; the anchor list.
2. Picture: an array (7 rows of 8 dots) split into 7 × 4 and 7 × 4.
3. Table: the 12 × 12 grid with the anchors coloured; he fills the rest from them.
4. Story: 8 teams of 7 players; 56 players into teams of 8.
5. Teach it: he teaches the coach a trick for one hard fact.

## Check by explaining back
"How do you get 7 × 8 fast if you forget it?"') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('LU.G.3', '# Verb tense to convey time, sequence, state and condition (LU.G.3, L.5.1c)

## The idea (in small steps)
1. The verb tense is the time stamp of a sentence: past (walked), present (walk / walks), future (will walk).
2. Time words are clues: yesterday, last week → past; every day, usually → present habit; tomorrow, next year → future.
3. Sequence: when two past actions happen one before the other, the earlier one uses had + past participle (past perfect): "By the time the bell rang, Leyla had finished."
4. State: the present perfect (has/have + participle) shows something that started in the past and is still true: "I have lived in Baku for ten years" (still here). Simple past means it is finished.
5. Condition: "if … will …" says what would happen only if something else happens: "If it rains, we will stay inside."

## Worked example
"Every summer my cousins ___ to Sheki, and they ___ there again next year." First blank: a habit → simple present: go. Second: "next year" → future: will go. Full sentence: "Every summer my cousins go to Sheki, and they will go there again next year."

## Faded example (he completes)
"Kamran ate breakfast and left for school." Show that eating happened first: "Kamran ___ ___ breakfast before he left for school." (Answer: had eaten.)

## Anticipated errors (and the scaffold)
- Using the present for a past story ("Yesterday he goes"). Scaffold: "Find the time word. When did it happen?"
- Irregular past forms (eated, goed). Scaffold: keep a list — eat/ate, go/went, run/ran.
- Using simple past for a sequence where past perfect is needed. Scaffold: "Which happened first? That one gets ''had''."
- Present perfect vs simple past for state. Scaffold: "Is it still true now?"

## Representation sequence
1. Words: three time stamps, then the two special forms (had…, has/have…).
2. Picture: a timeline with now in the middle; place each sentence on it.
3. Table: time word | tense | example.
4. Story: he tells what he did yesterday, does every day, and will do tomorrow — one sentence each.
5. Teach it: he explains to a younger child why "I have lived" and "I lived" are different.

## Check by explaining back
"How does the verb tell the reader when something happened?"') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('LU.G.4', '# Recognise and correct inappropriate shifts in verb tense (LU.G.4, L.5.1d)

## The idea (in small steps)
1. A piece of writing usually stays in one tense. If a story starts in the past, it stays in the past unless the time really changes.
2. An inappropriate shift is when the tense changes for no reason: "She opened the door and walks in."
3. To check: underline every verb, write P (past), Pr (present) or F (future) above it, and look for odd ones out.
4. Fix the odd one by matching it to the others — usually the first verb sets the tense.
5. A shift is correct when the time really changes: "Yesterday I lost my key, but I will look for it tomorrow."

## Worked example
"Last Saturday we visit the museum. The guide showed us a golden helmet, and everyone gasps. Then we ate lunch in the garden." Verbs: visit (Pr), showed (P), gasps (Pr), ate (P). "Last Saturday" sets the past. Fix: visit → visited; gasps → gasped.

## Faded example (he completes)
"Murad picks up the ball, ran to the goal and scores." Tenses: picks (___), ran (___), scores (___). Choose one tense for all three: ___ . Rewrite: ___ . (Answers: Pr, P, Pr; present or past; "Murad picks up the ball, runs to the goal and scores" / "picked, ran, scored".)

## Anticipated errors (and the scaffold)
- Fixing only one verb and leaving another. Scaffold: "Mark every verb first, then fix."
- Changing the wrong one (making everything present in a "last Saturday" story). Scaffold: "Which time word is in the sentence?"
- Thinking every change of tense is a mistake. Scaffold: "Did the time actually change? Then it is allowed."
- Reported speech: "She said she will come." Scaffold: "After ''said'', will becomes would."

## Representation sequence
1. Words: mark P / Pr / F above the verbs.
2. Picture: a timeline; verbs that jump off the line are suspects.
3. Table: verb | tense | matches the others?
4. Story: he writes four sentences about a match in the past, then checks them with the marks.
5. Teach it: he finds the shift in the coach''s deliberately wrong sentence and explains it.

## Check by explaining back
"How do you find a verb that has changed tense by mistake?"') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('LU.G.6', '# Subject–verb agreement; pronoun–antecedent agreement; run-ons and fragments (LU.G.6, L.4.1 review)

## The idea (in small steps)
1. Subject–verb agreement: one thing → verb with -s (the cat sleeps); more than one → no -s (the cats sleep). "Is/was" for one, "are/were" for many.
2. Pronoun agreement: a pronoun matches the noun it stands for: Leyla → her; the boys → their; each (one at a time) → his or her.
3. A complete sentence needs a subject and a verb and must make sense on its own. "Running down the hill." is a fragment.
4. A run-on joins two complete sentences without the right glue: "I finished my homework, then I went outside." Fix with a full stop, a comma + and/but/so, or a joining word like because/after.
5. Tricky subjects: neither/nor → agree with the nearer noun; a team, a class → one thing (is, its).

## Worked example
"Neither the teacher nor the students ___ ready." The noun nearest the verb is "students" (many) → were. "The team is practising ___ new song" → team is one thing → its. "The match started late it was raining the players were cold" → three sentences: "The match started late because it was raining, and the players were cold."

## Faded example (he completes)
"Each of the boys brought ___ own lunch." Each = one at a time → ___ . "The cats ___ sleeping" → ___ . Fragment or sentence: "Because it was late." → ___ . (Answers: his; are; fragment.)

## Anticipated errors (and the scaffold)
- Matching the verb to the nearest noun instead of the subject ("The box of pens are…"). Scaffold: "What is doing the action? Box. One box → is."
- "Their" with "each/every". Scaffold: "Each means one at a time."
- Comma splices. Scaffold: "Two full sentences? A comma alone can''t hold them."
- Calling a long fragment a sentence because it is long. Scaffold: "Who is doing what? Does it make sense alone?"

## Representation sequence
1. Words: the three questions — one or many? who does the pronoun stand for? complete or not?
2. Picture: circle the subject, draw an arrow to its verb; draw an arrow from each pronoun back to its noun.
3. Table: subject | one/many | verb.
4. Story: he fixes a short paragraph with one of each error.
5. Teach it: he explains a run-on to a younger child with two toy cars that need a hook (the joining word).

## Check by explaining back
"How do you decide between ''is'' and ''are''? How do you fix a run-on?"') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('LU.M.6', '# Capitalisation; punctuating dialogue with quotation marks and commas (LU.M.6, L.4.2 review)

## The idea (in small steps)
1. Capital letters: the first word of a sentence; names of people and places; days, months, holidays; titles like Mr; the word I. Not ordinary nouns (aunt, museum, book) and not seasons.
2. Dialogue: the words a person says go inside quotation marks: "Let''s go," said Murad.
3. A comma separates the speech from the speaker tag, and it sits inside the closing quotation mark: "Let''s go," — not "Let''s go",
4. Question and exclamation marks replace the comma and also stay inside: "Can we go?" asked Aysel.
5. The speech starts with a capital letter. When the tag comes first, put the comma after it: Aysel asked, "Can we go?"
6. A new speaker starts a new line.

## Worked example
"the coach shouted keep running elchin" → The coach shouted, "Keep running, Elchin!" Capital T (first word), comma after shouted, opening marks, capital K, a comma before the name (direct address), exclamation mark inside the closing marks.

## Faded example (he completes)
aysel asked can we go to the park → ___ asked, "___ we go to the park___" (Answers: Aysel; Can; ?" — question mark inside the marks.)

## Anticipated errors (and the scaffold)
- Capitalising every important-sounding noun ("my Aunt", "the Museum"). Scaffold: "Is it the actual name of one particular person or place?"
- Comma outside the quotation marks. Scaffold: "The comma lives inside the house."
- No comma between speech and tag. Scaffold: "Speech, comma, tag — or tag, comma, speech."
- Lower-case start inside the quotation. Scaffold: "Speech starts like a sentence."
- Interrupted speech: "If we leave now," said Nigar, "we will catch the bus." — the second part is lower case because it continues the sentence. Scaffold: "Is it one sentence split in two?"

## Representation sequence
1. Words: the capital-letter list; the "comma inside" rule.
2. Picture: draw the quotation marks as a house; the punctuation is furniture inside.
3. Table: sentence | what needs a capital | what needs marks/commas.
4. Story: he writes a four-line conversation between two characters from a passage.
5. Teach it: he corrects the coach''s deliberately unpunctuated dialogue.

## Check by explaining back
"Where does the comma go when someone speaks, and why does the speech start with a capital?"') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('LU.S.1', '# Expand, combine and reduce sentences for meaning, interest and style (LU.S.1, L.5.3a)

## The idea (in small steps)
1. Expand: add detail that answers when, where, how, why: "The bird sang" → "At dawn, the small bird sang sweetly from the fig tree."
2. Combine: join two short sentences with a comma + and/but/so, or with a joining word that shows the relationship: because (reason), when/after (time), although (contrast).
3. Reduce: cut words that add nothing: "at this point in time" → "now"; "are of the opinion that" → "think".
4. Style: vary sentence length — a long sentence followed by a short one makes the short one hit harder.
5. Read it aloud: if you run out of breath or stumble, revise.

## Worked example
"Sabina opened the box. It was empty. She was surprised. She had expected a gift." Combine and reduce into two sentences: "When Sabina opened the box, she was surprised to find it empty. She had expected a gift." The time word "when" links the first two ideas; the short second sentence explains the surprise.

## Faded example (he completes)
Combine to show the reason: "Kamran was late. His bus broke down." → "Kamran was late ___ his bus broke down." Now expand "The children played" with a when and a where: "___, the children played ___." (Answers: because; After school / in the courtyard — any sensible choice.)

## Anticipated errors (and the scaffold)
- Combining with "and… and… and". Scaffold: "What is the relationship — reason, time, contrast? Use that word."
- Comma splice when combining. Scaffold: "Comma needs a partner: and, but, so."
- Expanding with empty words ("very very big"). Scaffold: "Add a detail, not a volume knob."
- Reducing until the meaning is lost. Scaffold: "Say the sentence back — is anything important missing?"

## Representation sequence
1. Words: three verbs — expand, combine, reduce — and what each does.
2. Picture: a sentence "skeleton" with slots for when/where/how/why.
3. Table: short sentences | joining word | combined sentence.
4. Story: he takes three lines from his own writing and improves each with one move.
5. Teach it: he shows a younger child how two toy-block sentences click together with a joining word.

## Check by explaining back
"When you join two sentences, how do you choose the joining word?"') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('LU.W.ID', '# Writer''s notebook habit; generates ideas; sets writing goals (LU.W.ID, QSI Writing E01)

## The idea (in small steps)
1. Writers collect before they write. A notebook catches ideas, overheard lines, odd facts and small observations before they disappear.
2. Ideas come from noticing: a man feeding pigeons with one hand while reading a letter; a shop with a blue door. Ask "what if?" and "why?" to turn an observation into a story.
3. Keep entries short — a line or two is enough. Date them.
4. Set one writing goal at a time and make it checkable: "use dialogue in every story this month", "write ten minutes every day", "stop using the word very".
5. Look back every week: which idea could become a story? Is the goal being met? What is the next goal?

## Worked example
Entry: "Saw an old man feeding pigeons with one hand while reading a letter with the other. He looked worried." What if the letter is from someone he has not seen in fifty years? Why is he worried? Story seed: an old man, a letter, a decision to make by sunset. Goal for the month: "Every story I write will have a real ending that shows a change." Check: reread each story''s last paragraph on Friday.

## Faded example (he completes)
Write three story ideas in one line each, each with a character and a problem: 1 ___ 2 ___ 3 ___. Choose one and write a goal for the week: ___ ; how you will check it: ___ .

## Anticipated errors (and the scaffold)
- Waiting for the perfect idea. Scaffold: "Write the small thing you noticed today. That is enough."
- Goals like "write better". Scaffold: "How many? How often? How will you know?"
- Notebook entries that are just titles. Scaffold: "One line about what happened, one question."
- Never rereading the notebook. Scaffold: Friday five minutes — circle one idea.

## Representation sequence
1. Words: notice → note → ask what if → goal.
2. Picture: the notebook page with date, observation, question.
3. Table: date | observation | what-if | possible story.
4. Story: he turns one of his own entries into a three-sentence story seed.
5. Teach it: he shows a younger child how to keep a "noticing" list.

## Check by explaining back
"How do you turn something you noticed into a story idea, and what makes a writing goal a good one?"') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('LU.W.N1', '# Orient the reader: situation, narrator, characters; natural event sequence (LU.W.N1, W.5.3a)

## The idea (in small steps)
1. The opening of a story answers three questions quickly: who is here, where and when are we, and what is going on?
2. Choose a narrator and keep it: first person (I) or third person (he/she/they).
3. Show the situation through action or detail, not by announcing it: "Murad checked his watch again" beats "Murad was worried about being late."
4. Events go in a natural order; each one leads to the next. Plan them as a list before writing.
5. One small problem in the first few sentences gives the reader a reason to keep reading.

## Worked example
"On a windy morning in Qala, ten-year-old Sabina waited on the beach for the race to begin." Who: Sabina, 10. Where/when: Qala beach, a windy morning. What: a race is about to start; the wind hints at trouble. Third-person narrator. Next events: the race starts → the wind blows out her candle → Kamran arrives.

## Faded example (he completes)
Write two opening sentences: sentence 1 names a character and a place (___); sentence 2 shows a small problem through an action (___). Then list three events in order: 1 ___ 2 ___ 3 ___.

## Anticipated errors (and the scaffold)
- Starting with "It was a normal day" or "Hi, my name is". Scaffold: "Start where something is about to happen."
- Switching narrator half-way (I → he). Scaffold: "Who is telling this? Keep the same voice."
- Events out of order (finding the key before losing it). Scaffold: "Number the events first."
- Telling the problem ("the problem was…"). Scaffold: "Show me the problem through what the character does."

## Representation sequence
1. Words: who, where/when, what — the three questions.
2. Picture: a story map — setting box, character box, problem box, arrow of events.
3. Table: event | what the reader learns | what it leads to.
4. Story: he rewrites a flat opening ("It was a day") as a scene.
5. Teach it: he explains to a younger child why a story needs a "who and where" at the start.

## Check by explaining back
"What must the first few sentences of a story tell the reader, and how can you show a problem without saying ''the problem was''?"') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('LU.W.N2', '# Dialogue, description and pacing to develop experiences and characters (LU.W.N2, W.5.3b)

## The idea (in small steps)
1. Dialogue shows who a character is by what they say and how: "Um… do we have to go in?" shows nerves without the word "nervous".
2. Description uses the senses to put the reader in the place: smells, sounds, light, texture.
3. Pacing is speed: slow down the important moment with small details and thoughts; speed up the boring parts by skipping them.
4. Show, don''t tell: replace "he was angry" with an action — "He slammed the book shut."
5. Every line of dialogue needs a reason: it reveals character, moves the story, or raises tension.

## Worked example
Telling: "Kamran was angry." Showing: "Kamran slammed his book shut and stared at the wall. ''Fine,'' he said. ''Do it yourself.''" The slam and the short cold sentence show the anger. Pacing a tense moment: "He reached for the handle. It was cold. Slowly, slowly, he turned it. Something moved on the other side."

## Faded example (he completes)
Show that Leyla is nervous before a test, without the word nervous: action ___ ; one line she says ___ ; one sensory detail of the room ___ .

## Anticipated errors (and the scaffold)
- Naming the feeling. Scaffold: "What would I SEE her do?"
- Dialogue that only says hello. Scaffold: "What does this line tell me about the character?"
- Everything at the same speed. Scaffold: "Where is the most important moment? Slow it down there."
- Description lists without sentences ("cold, dark, quiet"). Scaffold: "Put the details into the action."

## Representation sequence
1. Words: show, don''t tell; slow the big moment.
2. Picture: a speed line under the story — where does it slow, where does it race?
3. Table: feeling | action that shows it | line of dialogue.
4. Story: he rewrites one "told" sentence from his own writing as a shown moment.
5. Teach it: he acts out a feeling for the coach to guess, then writes the actions he used.

## Check by explaining back
"How can you show a character is worried without using the word?"') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('LU.W.N3', '# Transitional words for sequence; concrete words and sensory details (LU.W.N3, W.5.3c-d)

## The idea (in small steps)
1. Transitions are signposts that show order and time: first, then, next, after that, meanwhile, as soon as, finally, the next morning.
2. Use them to move between events and between scenes; without them the reader gets lost.
3. Concrete words are exact: "fox darted" instead of "animal ran"; "cinnamon" instead of "nice smell".
4. Sensory details use the five senses; two or three well-chosen ones beat a list of ten.
5. Check a paragraph: circle the transitions (are there any?), underline vague words (replace them), tick the senses used.

## Worked example
"We packed the car. We drove to Gabala. We set up the tent. It started to rain." → "First we packed the car, and then we drove north to Gabala. As soon as we had set up the tent, fat drops of rain began to drum on the canvas." Transitions: first, then, as soon as. Concrete: north, fat drops, drum, canvas. Senses: sound and touch.

## Faded example (he completes)
Add a transition and a sensory detail: "The party ended. The classroom was quiet." → "The party ended late, and ___ morning the classroom ___ (sound or sight detail)." (Example: the next; smelled of chalk and felt very quiet.)

## Anticipated errors (and the scaffold)
- "Then… then… then…". Scaffold: "Vary the signposts — after that, meanwhile, finally."
- Vague nouns and verbs (thing, went, nice). Scaffold: "Which exact thing? How exactly did it move?"
- Overloading with adjectives ("the big red shiny fast new car"). Scaffold: "Two precise details."
- Senses as a list. Scaffold: "Put the detail into a sentence with an action."

## Representation sequence
1. Words: the signpost list; the five senses.
2. Picture: a road with signposts between scenes.
3. Table: vague word | concrete replacement.
4. Story: he describes the school canteen with three senses and two transitions.
5. Teach it: he shows a younger child how "animal" becomes "fox" and why it is better.

## Check by explaining back
"What do transition words do for the reader, and what makes a detail ''concrete''?"') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('LU.W.N4', '# A conclusion that follows from the events (LU.W.N4, W.5.3e)

## The idea (in small steps)
1. The ending must grow out of what happened; it cannot come from nowhere.
2. Three strong ways to end: show how the character has changed; return to an image or line from the beginning; let the character reflect briefly on what happened.
3. Resolve the problem you set up — found, not found, fixed, accepted — the reader needs to know.
4. Show the change through action or a small detail rather than announcing "I learned that…".
5. Stop at the right moment: one or two sentences after the resolution.

## Worked example
Beginning: "The old clock on the wall had not ticked in years." Ending: "As Nigar wound the last spring, the old clock ticked once, then again, and the house seemed to breathe." The ending returns to the clock, resolves the problem, and shows the change without explaining it.

## Faded example (he completes)
Rasim promised to water his grandmother''s garden and forgot for three days. Write a two-sentence ending: sentence 1 shows what he does about it (___); sentence 2 shows what has changed in him (___).

## Anticipated errors (and the scaffold)
- "The end" or "then I woke up". Scaffold: "What happened to the problem?"
- A moral tacked on ("I learned that honesty is good"). Scaffold: "Show me the lesson in what he does next."
- An ending about something new (a dragon). Scaffold: "Which thread from the story does this tie up?"
- Ending too early or dragging on. Scaffold: "Find the last strong image and stop there."

## Representation sequence
1. Words: resolve, show change, echo the beginning.
2. Picture: a circle — the ending touches the start.
3. Table: problem | resolution | change shown by…
4. Story: he writes two different endings for the same story and chooses the stronger one.
5. Teach it: he explains to a younger child why "and then a dragon came" is a bad ending for a story about a lost key.

## Check by explaining back
"What are two ways to end a story so that it feels finished?"') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('LU.W.P1', '# Plan, draft, revise, edit with a checklist; task, purpose, audience (LU.W.P1, W.5.4–5)

## The idea (in small steps)
1. Before writing, decide the task (what kind of text), the purpose (to entertain, explain, persuade) and the audience (who will read it). These shape length, words and tone.
2. Plan: a short list — characters, setting, problem, three events, ending — or for non-fiction, the main points in order.
3. Draft: write it through without stopping to fix spelling. Get the ideas down.
4. Revise: change ideas and organisation — add detail, cut what does not help, reorder, improve the opening and ending. Use a checklist.
5. Edit: fix spelling, punctuation, capitals, tense. Read aloud to catch mistakes.
6. Revising and editing are different jobs done at different times.

## Worked example
Draft: "We went to the zoo. It was fun. We saw animals. Then we went home." Revision note: add specifics and feelings — which animals, what happened, why it was fun. Revised: "At the zoo, a baby elephant sprayed water over the fence and soaked my sister''s shoes. We laughed until the keeper asked us to move on." Edit: check capitals and full stops. Audience change: for six-year-olds, shorter sentences and a happy ending.

## Faded example (he completes)
Plan a story using the checklist: narrator ___; setting ___; problem ___; events 1 ___ 2 ___ 3 ___; ending ___ .

## Anticipated errors (and the scaffold)
- Editing spelling while drafting, losing the idea. Scaffold: "Ideas first, spelling later."
- "Revising" that only fixes commas. Scaffold: "Did any IDEA change?"
- No plan, so the story wanders. Scaffold: the five-line plan.
- Same style for every audience. Scaffold: "Who is reading this? What do they need?"

## Representation sequence
1. Words: the five steps as a chant — plan, draft, revise, edit, share.
2. Picture: a staircase with the five steps; a checklist on the revise step.
3. Table: draft sentence | revision question | improved sentence.
4. Story: he revises one paragraph of his own school writing with two revision questions.
5. Teach it: he explains to a younger child the difference between revising and editing using a drawing (change the picture vs clean the smudges).

## Check by explaining back
"What is the difference between revising and editing, and which comes first?"') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('RD.HAB', '# Reading habit: chooses books, sets goals, reads 20+ minutes daily, keeps a log (RD.HAB, QSI Reading E01)

## The idea (in small steps)
1. Readers get better by reading — 20 minutes every day is the single strongest habit for reading scores. The app tracks passages; books count too.
2. Choosing a book: use the five-finger rule — read one page; if five or more words are unknown, it is too hard for now; if none, it may be too easy for growth.
3. Set a goal you can measure: "20 minutes a day, 5 days a week" or "finish this book by Friday".
4. Keep a log: date, title, pages or minutes, one sentence about what happened or what you thought. The log is for you, not for marks.
5. Talk about what you read: tell someone one thing you liked and one question you have.

## Worked example
Elchin picks a book about the sea. Page one has two unknown words — a good fit. Goal: 20 minutes after homework, Monday to Friday. Log entry: "9 Sep — The Sea Book, 14 pages. Whales sing to each other across the ocean. Question: how far can the sound travel?" Weekly review with a parent: streak of days, one favourite moment.

## Faded example (he completes)
Write today''s log line: date ___, title ___, minutes ___, one sentence ___, one question ___ .

## Anticipated errors (and the scaffold)
- Choosing books that are far too hard (or only comics). Scaffold: five-finger rule; mix easy and stretch.
- Goals like "read more". Scaffold: "How many minutes, how many days?"
- Log entries that are just titles. Scaffold: "One sentence about the story, one question."
- Reading 60 minutes once a week instead of 20 daily. Scaffold: "Daily is the magic; a little every day."

## Representation sequence
1. Words: the habit rule — 20 minutes, every day, a book you chose.
2. Picture: a calendar chain — do not break the chain.
3. Table: the reading log itself.
4. Story: he recommends a book to the coach in three sentences.
5. Teach it: he explains the five-finger rule to a younger child.

## Check by explaining back
"How do you choose a book that is right for you, and how do you know you are keeping your goal?"') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('RD.RF.4', '# Read grade-level text with accuracy, rate and expression — oral, timed (RD.RF.4, RF.5.4)

## The idea (in small steps)
1. Fluent reading has three parts: accuracy (the right words), rate (a natural speed, not racing), and expression (your voice shows the meaning and the punctuation).
2. Read a short passage once silently to know the story; then read it aloud.
3. Punctuation is a script: a full stop means stop and breathe; a comma means a small pause; a question mark lifts your voice; quotation marks mean a character is speaking — change your voice a little.
4. If you stumble on a word, stop, fix it, and reread the whole phrase.
5. Grade-5 target: about 120–150 correct words per minute with expression, on a familiar passage. Speed is a result of accuracy, not the goal.

## Worked example
"''Step back,'' said the white goat, ''because I was already on the bridge before you.''" Read: a firm, slightly bossy voice for the goat''s words; a normal voice for "said the white goat"; pause at the commas; the sentence rises at "back" because it is a command. Then time a 100-word chunk: count words read, subtract errors, note the seconds.

## Faded example (he completes)
Practise this sentence three ways: flat, then with pauses at commas, then with a character voice for the quotation. Which one sounds like someone telling a story? ___ . Now do the same with the next sentence. (Answer: the third.)

## Anticipated errors (and the scaffold)
- Racing to be fast and skipping small words. Scaffold: "Slower and right beats fast and wrong. Reread that line."
- Ignoring punctuation — one long breath. Scaffold: tap the table at every full stop.
- Monotone. Scaffold: "How does the goat feel? Make your voice show it."
- Guessing long words from the first letters. Scaffold: "Break it: ex-haus-ted."

## Representation sequence
1. Words: the three parts — accurate, steady, expressive.
2. Picture: mark the passage — slashes at pauses, arrows for voice up/down, wavy line under speech.
3. Table: date | passage | words per minute | errors | expression score (1–3), kept weekly by the parent.
4. Story: he reads a fable to a family member as a performance.
5. Teach it: he coaches a younger child to read a sentence with feeling.

## Check by explaining back
"What do the commas and quotation marks tell your voice to do?"') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('RD.RL.1', '# Quote accurately from a text; draw inferences with evidence (RD.RL.1, RL.5.1)

## The idea (in small steps)
1. Two kinds of questions: "right there" (the answer is written in the text) and "think and search" (you combine clues to infer).
2. Routine for every question: read the question, find the evidence, quote it, then answer. Evidence first, answer second.
3. Quoting means copying the exact words inside quotation marks. Paraphrasing is saying it in your own words — different job.
4. An inference is a sensible conclusion from clues plus what you already know. It must be supported by something in the text.
5. Say the sentence that connects them: "The text says ''…'', so I can tell that …".

## Worked example
Question: How do we know the goats regretted their fight? Find: "''We could easily have done that,'' said the white goat in a quiet voice." Quote it. Infer: a quiet voice and "could have" show he wishes they had acted differently. Answer: They regretted it; the quote shows it.

## Faded example (he completes)
Question: Was Tofiq sorry? Evidence sentence: "''You were right,'' he admitted quietly." Quote: ___ . Inference: the word ___ and the word ___ show he feels ___ . (Answers: the sentence; admitted; quietly; sorry / ashamed.)

## Anticipated errors (and the scaffold)
- Answering from memory of the story instead of the text. Scaffold: "Put your finger on the sentence."
- Quoting too much (a whole paragraph) or too little (two words). Scaffold: "One sentence that proves it."
- Changing words inside the quotation marks. Scaffold: "Copy exactly, comma for comma."
- Inference with no clue: "I think he was sad because I would be." Scaffold: "Which words in the text made you think that?"

## Representation sequence
1. Words: the four-step routine as a chant.
2. Picture: highlight the evidence in one colour, the answer in another.
3. Table: question | evidence quote | my inference.
4. Story: a detective — clues (quotes) lead to a conclusion (inference).
5. Teach it: he writes a "think and search" question about a passage for the coach to answer with a quote.

## Check by explaining back
"What is the difference between quoting and answering in your own words? When do you need each?"') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('RD.RL.2', '# Determine theme from details (how characters respond to challenges); summarise (RD.RL.2, RL.5.2)

## The idea (in small steps)
1. A topic is one or two words (friendship, honesty). A theme is a full sentence about life that the story shows (helping a friend can matter more than winning).
2. To find the theme, look at the challenge the main character faces and how they respond — and what happens because of that response.
3. Ask: what did the character learn, or what did the story show us? Say it as a sentence that would still be true in another story.
4. A summary is short: who, wanted what, what got in the way, what happened. No small details, no opinions.
5. The theme is never stated as "the story is about a goat" — that is the topic.

## Worked example
The Lantern Race: challenge — Sabina''s candle goes out. Response — Kamran relights it and gives up his chance; Sabina refuses to leave him. Result — they finish last but share a prize she treasures. Theme: helping a friend can matter more than winning. Summary: Sabina and Kamran run a lantern race; when her flame dies, he relights it and they finish together, last but happy.

## Faded example (he completes)
The Ant Who Saved the Summer. Challenge: winter comes and Tofiq has ___ . Response: he ___ and Nara ___ . Theme: ___ . (Answers: no food; admits he was wrong / asks for help; forgives him but makes him promise to work; prepare in good times for hard times.)

## Anticipated errors (and the scaffold)
- Giving the topic as the theme ("it''s about friendship"). Scaffold: "What does the story say ABOUT friendship? Make it a sentence."
- Retelling the whole story as a summary. Scaffold: "Four parts only: who, wanted, but, so."
- A theme that is a detail ("goats fall in rivers"). Scaffold: "Would this sentence be true in a different story too?"
- Choosing a moral the text does not support. Scaffold: "Which event shows that?"

## Representation sequence
1. Words: topic vs theme — one word vs one sentence.
2. Picture: a bridge — challenge on one side, response in the middle, lesson on the other.
3. Table: character | challenge | response | result | theme.
4. Story: two different stories with the same theme — what do they share?
5. Teach it: he explains to a younger child why "friendship" is not a theme.

## Check by explaining back
"Tell me the theme of the story we read, and which event proves it."') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('RD.RL.3', '# Compare and contrast characters, settings, events using details (RD.RL.3, RL.5.3)

## The idea (in small steps)
1. Compare = how they are alike. Contrast = how they are different. Most questions want both.
2. Pick a feature to compare (what they want, how they act, where they are, what they say) and find a detail for each side.
3. Use the text, not your imagination: "Sabina trained every evening" vs "Kamran built a windproof lantern".
4. Sentence frames: "Both … but …", "While A …, B …", "Unlike A, B …".
5. When a character changes, compare the same character at the beginning and at the end.

## Worked example
Sabina and Kamran. Feature: strengths. Sabina: "She could run the entire length of the beach without pausing." Kamran: "clever with his hands and patient with details." Alike: both want to reach the tower with a lit lantern. Different: her strength is speed; his is craft. Sentence: "While Sabina is the faster runner, Kamran is the better builder, and in the end they need both."

## Faded example (he completes)
Tofiq at the beginning: he ___ in the shade and ___ at Nara. Tofiq at the end: he is the ___ ant through the door and carries ___ seeds. Sentence: "At first Tofiq …, but by spring he …". (Answers: lies / rests; laughs; first; two.)

## Anticipated errors (and the scaffold)
- Listing facts about each without linking them. Scaffold: "Use ''but'' or ''while'' to join the two."
- Comparing different features (her speed vs his kindness). Scaffold: "Same feature on both sides."
- No evidence. Scaffold: "Which sentence shows that?"
- Only differences. Scaffold: "Name one thing they share first."

## Representation sequence
1. Words: the sentence frames.
2. Picture: a Venn diagram — shared in the middle.
3. Table: feature | character A (quote) | character B (quote).
4. Story: he compares two people he knows using the same table.
5. Teach it: he explains a Venn diagram to a younger child with two animals.

## Check by explaining back
"Give me one way the two characters are alike and one way they are different, with a detail for each."') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('RD.RL.4', '# Meaning of words and phrases, including figurative language — metaphor and simile (RD.RL.4, RL.5.4)

## The idea (in small steps)
1. Literal language means exactly what it says. Figurative language paints a picture to make you feel or see something.
2. A simile compares using "like" or "as": "as flat and heavy as a brick."
3. A metaphor says one thing IS another: "the lanterns were small moons" — they are not really moons.
4. To explain a figurative phrase, ask: what two things are compared, and what do they share? Then say the plain meaning.
5. Writers use them to show how bad, how big, how quiet — with feeling.

## Worked example
"A loaf as flat and heavy as a brick." Two things: the loaf and a brick. Shared: flat, heavy, hard. Plain meaning: the bread failed completely. It is a simile because of "as … as". Why the author chose it: a brick is the opposite of what bread should be, so we feel Rasim''s disappointment.

## Faded example (he completes)
"Their lanterns glowing like miniature moons." Two things compared: ___ and ___ . Shared: ___ . Simile or metaphor? ___ because of the word ___ . (Answers: lanterns; moons; round, glowing, small in the dark; simile; like.)

## Anticipated errors (and the scaffold)
- Taking it literally ("the bread was made of clay"). Scaffold: "Is the writer telling a fact, or making a picture?"
- Mixing simile and metaphor. Scaffold: "Is there a ''like'' or ''as''?"
- Explaining the comparison but not the meaning. Scaffold: "So what is the writer really saying about the bread?"
- Idioms ("busy being right") read word by word. Scaffold: "What does the whole phrase mean together?"

## Representation sequence
1. Words: the two definitions with the test words like/as.
2. Picture: draw the literal picture (a brick loaf) next to the real meaning.
3. Table: phrase | two things | shared | plain meaning | simile or metaphor.
4. Story: he describes his school day with one simile and one metaphor.
5. Teach it: he explains to a younger child why "the classroom was a zoo" is not about animals.

## Check by explaining back
"What is the difference between a simile and a metaphor? Give me one of each."') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('RD.RL.6', '# Narrator''s or speaker''s point of view and how it shapes events (RD.RL.6, RL.5.6)

## The idea (in small steps)
1. The narrator is the voice telling the story. Ask: is the narrator a character (first person: I, me, we) or outside the story (third person: he, she, they)?
2. A first-person narrator only knows their own thoughts and what they see; we trust or doubt them as we would a friend telling a story.
3. A third-person narrator can follow one character closely (we know Rasim''s burning face) or several.
4. Point of view shapes what we learn and how we feel: if the story followed Master Farid, we would know his plan and feel less worried.
5. To answer questions: name the narrator type, then say what that lets us know — and what it hides.

## Worked example
The Baker''s Apprentice is told in the third person but follows Rasim: we know his face burns and he wants to hide the loaf. We do not know what Farid is thinking, so Farid''s laugh is a surprise to us just as it is to Rasim. That surprise is the point of the story.

## Faded example (he completes)
The Crow and the Water Jar. Narrator: first or third person? ___ . Whose feelings do we know? ___ . What would change if the sparrow told the story? We would ___ . (Answers: third; the crow''s; only see the crow from outside and not know her thinking / plan.)

## Anticipated errors (and the scaffold)
- Saying the narrator is "the author". Scaffold: "The author writes; the narrator is the voice inside the story. Are they the same person here?"
- Confusing a character who speaks a lot with the narrator. Scaffold: "Who says ''I''? Who tells us what happened?"
- Answering only "third person" without the effect. Scaffold: "And so what do we get to know that the characters don''t?"
- Thinking the narrator''s view is always right. Scaffold: "Could a first-person narrator be mistaken?"

## Representation sequence
1. Words: the pronoun test (I/we vs he/she/they).
2. Picture: a camera — where is it standing? inside one head, or above the scene?
3. Table: narrator type | what we know | what we don''t | effect.
4. Story: retell one scene from another character''s point of view.
5. Teach it: he explains to a younger child how the same event sounds different told by the black goat.

## Check by explaining back
"How would the lantern story change if Kamran told it?"') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('RD.V.1', '# Context clues to find word meaning (RD.V.1, L.5.4a)

## The idea (in small steps)
1. Do not stop at a hard word: read the whole sentence and the one before and after. The clues are around it.
2. Clue types: a definition or restatement ("evaporation, which means…"), an example, a contrast ("but", "unlike"), a cause and effect ("because she…, she felt…"), and the general feeling of the sentence.
3. Replace the word with your guess and reread. Does the sentence still make sense?
4. Check with the part of speech: is it a thing, an action, or a describing word?
5. Only after that, use a dictionary — and choose the meaning that fits the sentence.

## Worked example
"They scrambled to the bank, dripping and ashamed, while the birds laughed from the trees." Clues: they just fell in after a silly fight; birds are laughing at them; "dripping" is a feeling-of-embarrassment situation. Guess: ashamed = embarrassed about what they did. Replace and reread: "dripping and embarrassed" — makes sense. Part of speech: describing word. Confirmed.

## Faded example (he completes)
"Her candle flickered twice and went out." Clue: it "went out" straight after. So "flickered" probably means the flame ___ . Replace: "the candle ___ twice and went out." (Answers: wobbled / shook unsteadily; wobbled.)

## Anticipated errors (and the scaffold)
- Guessing from the look of the word (ashamed → "a shame" → "a pity"). Scaffold: "Use the sentence, not the letters."
- Skipping the word and never coming back. Scaffold: "Circle it, finish the sentence, then go back."
- Picking a dictionary meaning that does not fit ("bank" = money place). Scaffold: "Reread with that meaning — does it work?"
- A guess with the wrong part of speech. Scaffold: "Is it an action here, or a thing?"

## Representation sequence
1. Words: the five clue types as a checklist.
2. Picture: the hard word in a box with arrows from the clue words around it.
3. Table: word | clues | guess | reread check.
4. Story: he invents a nonsense word in a sentence and the coach works out what it means from clues.
5. Teach it: he shows a younger child how to "read around" a word.

## Check by explaining back
"What do you do when you meet a word you don''t know?"') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
insert into explanations (skill_id, body) values ('SC.PRAC.1', '# Read tables and graphs; identify variables; plan a fair test; draw conclusions from data (SC.PRAC.1, NGSS practices)

## The idea (in small steps)
1. A table has a heading for each column: read the headings first, then the numbers. A graph has axes with labels and units: read those first too.
2. A pattern is what the numbers do as you move along: up, down, steady, or up-then-down.
3. In an experiment there is one thing you change on purpose (the independent variable), one thing you measure (the dependent variable), and everything else you keep the same (controls).
4. A fair test changes only one thing. If two things change, you cannot tell which one caused the result.
5. A conclusion says what the data shows — no more. "Ice melted fastest in the sun" is supported; "the sun makes everything melt" is not.
6. Repeating a test makes the result more reliable.

## Worked example
Table: ramp height 10 cm → car rolls 40 cm; 20 cm → 80 cm; 30 cm → 120 cm. Headings: height, distance. Pattern: every extra 10 cm of height adds 40 cm of distance — distance goes up steadily. Variables: changed = height; measured = distance; kept the same = the car, the floor, the release. Conclusion: a higher ramp makes the car roll further. Prediction: 40 cm → about 160 cm.

## Faded example (he completes)
Sugar dissolving: hot water 20 s, warm 45 s, cold 120 s. Changed: ___ . Measured: ___ . Kept the same: ___, ___ . Conclusion: sugar dissolves faster when ___ . (Answers: temperature; time to dissolve; amount of sugar, amount of water, stirring; the water is hotter.)

## Anticipated errors (and the scaffold)
- Reading a number without its heading or unit. Scaffold: "40 what? Which column?"
- Changing two things "to make it faster". Scaffold: "Then which one did it?"
- A conclusion bigger than the data. Scaffold: "Point to the numbers that prove that sentence."
- Confusing what you change with what you measure. Scaffold: "Which one did YOU decide before starting?"

## Representation sequence
1. Words: change one, measure one, keep the rest.
2. Picture: sketch the graph from the table; draw the trend with a finger.
3. Table: variable | changed / measured / kept same.
4. Story: a fair test of two footballs — he designs it.
5. Teach it: he explains to a younger child why a race with different starting lines is unfair — and links it to fair tests.

## Check by explaining back
"What makes a test fair, and what can a conclusion say?"') on conflict (skill_id) do update set body = excluded.body, updated_at = now();
